### ISSUE TITLE
Looking for a maintainer

### ISSUE THREAD

**Issue by vicky002** [vicky002/AlgoWiki#305]
Hi Developers, 

I'm looking for a maintainer who can help me with reviewing PRs, commenting on questions and doing basic maintenance. 

I have been very busy lately with my startup and it's hard for me to focus on my Open Souce projects as well as my company. I'm looking for two developers who are very active on GitHub and love Open Source. It's the project I had started when I was in college to help other students and if you believe in helping others while learning, please comment and write:

- Why you are a perfect fit for this project?
- What is your availability? How frequently do you check Github?
- What is your timezone?
- Anything project that you have worked on or contributed to that I can take a look at? 🙂

I'll check the comments and reply as soon as I can. ONLY TWO SLOTS ARE AVAILABLE.

**Comment by xlogix** [comment]
My name is Abhishek Uniyal, a lifelong learner with the goal to improve the things I make and do.

- I'm the perfect fit for the project because I am working on a project which is trying to organize and recommend resources for learners according to their learning preferences. The project is called [footsteps](https://footsteps.dev), a personal tracker & curator of learning resources to learn anything.
- I check Github every day and I will be able to spend my time according to the project's need.
- My timezone is GMT +5:30 (IST)
- Definitely! Here are some of them:
   - [Interview TechDevGuide](https://github.com/fnplus/interview-techdev-guide)
   - [Curriculum](https://github.com/fnplus/curriculum)
   - [Footsteps-app](https://github.com/fnplus/footsteps-app)
   - [Footsteps-extension](https://github.com/fnplus/footsteps-extension)

**Comment by PragatiVerma18** [comment]
Hi there!! My name is Pragati Verma. I am an aspiring full-stack web developer and a student in second year of my B.Tech in computer science. I am an Open Source Enthusiast and I am eager to work on more project ideas that solve some real-world problems.

I am a perfect fit for the project because I have been working on my own <a href="https://github.com/Open-Source-Contributors-JSS/Hacktoberfest2019">Hacktoberfest2019</a> repo that earned 233 stars and 473 forks in the very first week of October, hence, I know how to respond to the issues an pull requests on an open-source project.

Also, I am active on GitHub which means I can daily review and respond on the issues and pull requests.

My timezone is GMT +5:30 (IST)

Here is the link to my GitHub Profile which has links to all my projects:
<a href="https://github.com/PragatiVerma18">https://github.com/PragatiVerma18</a>

Some of my notable projects are:
<ul>
<li><a href="https://weather-app-django.herokuapp.com/">Weather App Django</a></li>
<li><a href="https://youtube-search-django.herokuapp.com/">YouTube search</a></li>
<li><a href="https://pragativerma18.github.io/Tasks-List/">Tasks List</a></li>
</ul>

**Comment by codingonHP** [comment]
### Why you are a perfect fit for this project?
One reason I like this project is that its a resource aggregator spaning to multiple ecosystem.
I can use it for myself and I have a pending PR as well :)
I would like to contribute as a maintainer and there are about 40 PRs open I have already
gone through most of them!

### What is your availability? How frequently do you check Github?
I am available daily and I check my GitHub and Discord hourly

### What is your timezone?
IST

### Anything project that you have worked on or contributed to that I can take a look at?
Sure look at my GitHub profile

**Comment by vicky002** [comment]
@codingonHP @xlogix @PragatiVerma18  you have been added as collaborators on the AlgoWiki project. Please make it great. 

Also, we need to build a small website for this project. I would like you all to discuss, plan and build the site.

**Comment by vicky002** [comment]
I'm going to invite you all to our Slack channel where we will discuss and plan our website.
